
 const GET_SELLER='GET_SELLER';
 const SHOW_DETAIL='SHOW_DETAIL';
 const HIDE_DETAIL='HIDE_DETAIL';

 const GET_GOODS='GET_GOODS';

 const SHOW_FOOD='SHOW_FOOD';
 const HIDE_FOOD='HIDE_FOOD';

 const SELECT='SELECT';
 const CHANGE_TYPES='CHANGE_TYPES';
 const TOGGLE='TOGGLE';

 const GET_RATINGS='GET_RATINGS';

 export default {
 	GET_SELLER,
 	SHOW_DETAIL,
 	HIDE_DETAIL,
 	GET_GOODS,
 	SHOW_FOOD,
 	HIDE_FOOD,
 	SELECT,
 	CHANGE_TYPES,
 	TOGGLE,
 	GET_RATINGS
 }